### ISSUE TITLE
Sugerencia para deplegar en producción con un botón

### ISSUE THREAD

**Issue by gonzalo-bulnes** [MarioRamirez/bestsellers-acidlabs#1]
Hola @MarioRamirez!

Si tienes un ratito échale una mirada a [Introducing Heroku Button](https://blog.heroku.com/archives/2014/8/7/heroku-button), me tinca que te puede gustar. Puedes ver [un ejemplo aquí](https://github.com/gonzalo-bulnes/rails-api-authentication-demo/commit/a373bac70360766839b500dead66c9929d41a95e) si quieres.

Es encachado el botoncito, y además incita a desarrollar [12-factor](https://12factor.net/) apps, lo que es excelente.

Saludos!

**Comment by MarioRamirez** [comment]
No lo había visto antes, se agradece el aporte, ya lo apliqué. :+1:
